package example;

import javax.annotation.Nonnull;
import java.io.Serializable;
import java.util.Objects;

public class Message implements Serializable {
    private String id;

    public Message(@Nonnull String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }


    //Auto-generated by Intellij
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Message message = (Message) o;
        return id.equals(message.id);
    }

    //Auto-generated by Intellij
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
